version: '3.8'

services:
  # --- Servicio de Base de datos (PostgreSQL) ---
  db:
    image: postgres:15-alpine
    restart: always
    volumes:
      # Persistencia de datos: En caso de borrar los datos, los datos siguen aqu√≠
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      #Variables del .env
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"

  # --- Servicio de backend con FastAPI ---
  web:
    build: .
    # Comando apuntando a src
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
      - ./firebase_credentials.json:/app/firebase_credentials.json
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  postgres_data: